name = "DeviceSparseArrays"
uuid = "da3fe0eb-88a8-4d14-ae1a-857c283e9c70"
authors = ["Alberto Mercurio <alberto.mercurio96@gmail.com> and contributors"]
version = "0.1.0"

[deps]
AcceleratedKernels = "6a4ca0a5-0e36-4168-a932-d9be78d558f1"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"

[compat]
AcceleratedKernels = "0.4"
KernelAbstractions = "0.9"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "JET", "Test"]
