name = "DeviceSparseArrays"
uuid = "da3fe0eb-88a8-4d14-ae1a-857c283e9c70"
authors = ["Alberto Mercurio <alberto.mercurio96@gmail.com> and contributors"]
version = "0.1.0"

[deps]
AcceleratedKernels = "6a4ca0a5-0e36-4168-a932-d9be78d558f1"
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
ArrayInterface = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
AcceleratedKernels = "0.4"
Adapt = "4"
ArrayInterface = "7"
KernelAbstractions = "0.9"
LinearAlgebra = "1"
SparseArrays = "1"
julia = "1.10"
